PIDs:
  X:
    kp: 80.0
    kd: 60.0
    ki: 0.2
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: -80.0
    kd: -60.0
    ki: -0.2
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 7000.0
    kd: 8000.0
    ki: 400.0
    minOutput: 10000.0
    maxOutput: 60000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
  Yaw:
    kp: -700.0
    kd: -40.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0

#experimental play with kp x & y values until stable
